# Generated by Django 4.2.30 on 2026-04-15 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Arena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('arena', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.arena')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner_team', models.CharField(blank=True, max_length=50, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('lobby', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.lobby')),
            ],
        ),
        migrations.CreateModel(
            name='TankStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moveSpeed', models.FloatField(default=10.0)),
                ('maxHP', models.IntegerField(default=100)),
                ('reloadSpeed', models.FloatField(default=1.0)),
                ('rotationSpeed', models.FloatField(default=2.0)),
                ('turretRotationSpeed', models.FloatField(default=3.0)),
                ('bulletSpeed', models.FloatField(default=20.0)),
                ('bulletDamage', models.IntegerField(default=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('side', models.CharField(blank=True, max_length=50, null=True)),
                ('bodyModelKey', models.CharField(default='default_body', max_length=100)),
                ('turretModelKey', models.CharField(default='default_turret', max_length=100)),
                ('bulletModelKey', models.CharField(default='default_bullet', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('stats', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tanks', to='game.tankstats')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100, unique=True)),
                ('totalKills', models.IntegerField(default=0)),
                ('totalDeaths', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=1000)),
                ('selectedTank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.tank')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Obstacle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('rotationY', models.FloatField(default=0)),
                ('scaleX', models.FloatField(default=1)),
                ('scaleY', models.FloatField(default=1)),
                ('scaleZ', models.FloatField(default=1)),
                ('arena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obstacles', to='game.arena')),
            ],
        ),
        migrations.CreateModel(
            name='MatchPlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kills', models.IntegerField(default=0)),
                ('deaths', models.IntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='game.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.playerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='LobbyPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ready', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game.lobby')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.playerprofile')),
            ],
        ),
    ]
