# Generated by Django 4.2.30 on 2026-04-22 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_seed_catalog_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobbyplayer',
            name='side',
            field=models.CharField(default='allies', max_length=10),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='lastSeenAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='lobbyplayer',
            unique_together={('lobby', 'player')},
        ),
        migrations.CreateModel(
            name='LobbyInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fromPlayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_lobby_invites', to='game.playerprofile')),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='game.lobby')),
                ('toPlayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_lobby_invites', to='game.playerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fromPlayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_friend_requests', to='game.playerprofile')),
                ('toPlayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_friend_requests', to='game.playerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
