# Generated by Django 4.2.30 on 2026-04-22 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_lobbyplayer_side_playerprofile_lastseenat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='lobby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.lobby'),
        ),
    ]
